- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Install Java on server
      apt: 
        name: "{{ item }}"
        with_items:
          - curl
        status: present

